/**
 * Created by alin_balasa on 12-May-16.
 */

 console.log("●● expand.js");
	
 var selectors = {
     /* Selectors for the nodes that will contain an expand/collapse button. */
     "expand_buttons":[
     /* Table caption */
     /* "table > caption", */
     /* Article title */
     ".topic > .title",
     /* Section title. Exclude task labels generated by DITA-OT (EXM-37958 & EXM-38501).*/
     ".sectiontitle:not(.tasklabel)",
     /* Index terms groups */
     ".wh_term_group > .wh_first_letter"]
 };
 
 
     //   Add expand-collapse support.
 function preloadElements() {
     // 强制预加载所有图片（包括折叠区域内的）
     $('img[data-src], .carousel-inner img, .fig.carousel img').each(function() {
         const targetSrc = $(this).data('src') || $(this).attr('src');
         if (!targetSrc) return;
 
         // 关键：直接替换 src，绕过父级隐藏限制
         $(this).attr('src', targetSrc);
         
         // 虚拟加载兜底（兼容性）
         new Image().src = targetSrc;
     });
 }
     $(document).ready(function () { 
      /* Add the expand/collapse buttons. */
      selectors.expand_buttons.forEach(
      function (selector) {
          var matchedNodes = $(selector);
          // Add the expand/collapse support only if the title node has visible siblings.
          var visibleSiblings = matchedNodes.siblings(':not(:hidden)');// 所有不隐藏的兄弟
          if (visibleSiblings.length > 0) {
              // Add the element with expand/collapse capabilities
              matchedNodes.prepend("<span class=\"wh_expand_btn expanded\"/>");
              markHiddenSiblingsAsNotExpandable(matchedNodes);
          }
      });

     // 定义 mobileExpandHandler 处理函数
     function mobileExpandHandler(event) {
         var currentBtn = $(this);
         
         // 切换按钮状态及内容
         $(this).toggleClass("expanded");
         var siblings = $(this).parent().siblings(':not(.wh_not_expandable)');
         var tagName = $(this).parent().prop("tagName");
         if (tagName === "CAPTION") {
             siblings.toggle();
         } else {
            siblings.slideToggle(500);
         }
         
         // 预加载图片
         if ($(this).hasClass("expanded")) {
             siblings.find('img[data-src]').each(function () {
                 const targetSrc = $(this).data('src');
                 if (targetSrc) {
                     $(this).attr('src', targetSrc);
                     new Image().src = targetSrc; // 虚拟加载
                 }
             });
         }
         
         // 移动端逻辑：展开一个时关闭其他已展开的内容
         if ($(window).width() < 768) {
             var parentButtons = $(); // 存储需要保持展开的父级按钮
     
             // 检查当前按钮的标题级别
             var titleElement = currentBtn.closest('h2.title, h3.title, h4.title, h5.title, h3.sectiontitle, h4.title.sectiontitle');
             if (titleElement.length) {
                 var titleTag = titleElement.prop('tagName');
                 var titleClasses = titleElement.attr('class') || '';
                 
                 console.log('DEBUG 标题元素:', titleTag, '类:', titleClasses);
                 
                 // 对于H3,H4,H5，需要确保父级标题保持展开
                 if (titleTag !== 'H2' || titleClasses.includes('sectiontitle')) {
                     // 特殊处理section中的标题
                     if (titleClasses.includes('sectiontitle')) {
                         // 对于section中的标题，查找最近的.topic父容器中的标题按钮
                         var parentTopic = titleElement.closest('.topic');
                         if (parentTopic.length) {
                             var parentTitleBtn = parentTopic.find('> .title .wh_expand_btn');
                             if (parentTitleBtn.length) {
                                 parentButtons = parentButtons.add(parentTitleBtn);
                             }
                             
                             // 特别处理H4 sectiontitle，确保其直接父级topic的标题展开
                             if ((titleTag === 'H4' || titleTag === 'H3') && titleClasses.includes('sectiontitle')) {
                                 var sectionParent = titleElement.closest('.section');
                                 if (sectionParent.length) {
                                     var sectionParentTopic = sectionParent.closest('.topic');
                                     if (sectionParentTopic.length) {
                                         var sectionParentTitleBtn = sectionParentTopic.find('> .title .wh_expand_btn');
                                         if (sectionParentTitleBtn.length) {
                                             parentButtons = parentButtons.add(sectionParentTitleBtn);
                                         }
                                         
                                         // 还需要确保sectionParentTopic的父级也展开
                                         sectionParentTopic.parents('.topic').each(function() {
                                             var ancestorTitleBtn = $(this).find('> .title .wh_expand_btn');
                                             if (ancestorTitleBtn.length) {
                                                 parentButtons = parentButtons.add(ancestorTitleBtn);
                                             }
                                         });
                                     }
                                 }
                             }
                         }
                     } else {
                         // 对于普通的topic标题，查找所有父级topic中的标题按钮
                         titleElement.closest('.topic').parents('.topic').each(function() {
                             var parentTitleBtn = $(this).find('> .title .wh_expand_btn');
                             if (parentTitleBtn.length) {
                                 parentButtons = parentButtons.add(parentTitleBtn);
                             }
                         });
                     }
                 }
                 
                 // 特别处理H3标题 - 确保父级H2展开
                 if (titleTag === 'H3') {
                     var parentTopic = titleElement.closest('.topic');
                     if (parentTopic.length) {
                         var parentH2Btn = parentTopic.find('> h2.title .wh_expand_btn');
                         if (parentH2Btn.length) {
                             parentButtons = parentButtons.add(parentH2Btn);
                         }
                     }
                 }
             }
     
             console.log('DEBUG 需要保持展开的父级按钮数量:', parentButtons.length);
             
             // 排除当前按钮和父级按钮，收起其他所有展开的内容
             var excludeBtns = currentBtn.add(parentButtons);
             $('.wh_expand_btn.expanded').not(excludeBtns).each(function() {
                 console.log('DEBUG 收起按钮:', $(this).closest('h2, h3, h4').prop('tagName'));
                 $(this).removeClass("expanded");
                 $(this).parent().siblings(':not(.wh_not_expandable)').slideUp(500);
             });
             
             // 确保父级按钮都处于展开状态
             parentButtons.each(function() {
                 if (!$(this).hasClass('expanded')) {
                     console.log('DEBUG 展开父级按钮:', $(this).closest('h2, h3, h4').prop('tagName'));
                     $(this).addClass('expanded');
                     $(this).parent().siblings(':not(.wh_not_expandable)').slideDown(500);
                     
                     // 预加载父级内容中的图片
                     $(this).parent().siblings(':not(.wh_not_expandable)').find('img[data-src]').each(function () {
                         const targetSrc = $(this).data('src');
                         if (targetSrc) {
                             $(this).attr('src', targetSrc);
                             new Image().src = targetSrc; // 虚拟加载
                         }
                     });
                 }
             });
             
             // 视口补偿 - 滚动当前展开到视口顶部
             setTimeout(function() {
                 var currentTitle = currentBtn.closest('h2, h3, h4'); // 查找 currentBtn最近的父级标题元素。
                 if (currentTitle.length && currentBtn.hasClass('expanded')) {//检查是否找到了标题元素，并且当前按钮具有 expanded 类。
                     var offsetTop = currentTitle.offset().top; // 获取找到的标题元素距离页面顶部的距离。
                     var targetPosition = Math.max(0, offsetTop - 10); // 减去10像素确保完全可见
                     
                     console.log('DEBUG 视口补偿滚动到:', targetPosition);
                     $('html, body').animate({
                         scrollTop: targetPosition // 使用 animate，将页面滚动到计算出的目标位置，动画持续时间为 300 毫秒。
                     }, 300);
                 }
             }, 620); // 设置一个延迟执行的函数，延迟时间为 320 毫秒。这是为了确保在滚动之前，某些动画或内容折叠/展开操作已经完成。

         }
         
         event.stopImmediatePropagation();
         return false;
     }
         
     
     // 绑定点击事件 - 统一使用mobileExpandHandler处理所有情况
     $(document).find('.wh_expand_btn').click(mobileExpandHandler);
     
     // 标题点击事件 - 触发对应的按钮点击
     $(document).find('h2.title, h3.title, h4.title, h5.title, h3.sectiontitle, h4.title.sectiontitle').click(function (event) {
         var expandBtn = $(this).find('.wh_expand_btn');
         if (expandBtn.length > 0) {
             expandBtn.click();
         }
         event.stopImmediatePropagation();
         return false;
     });
     
     // 移动端初始化逻辑
     if ($(window).width() < 768) {
         // 检查是否为从其他页面跳转过来的
         var isFromOtherPage = false;
         var targetTopicId = '';
         
         // 检查URL中的hash（锚点）
         if (window.location.hash && window.location.hash.startsWith('#')) {
             targetTopicId = window.location.hash.substring(1);
             isFromOtherPage = true;
         }
         
         // 检查document.referrer来判断是否来自其他页面
         if (document.referrer && document.referrer !== window.location.href) {
             isFromOtherPage = true;
         }
         
         $('.wh_expand_btn').each(function () {
             var siblings = $(this).parent().siblings(':not(.wh_not_expandable)');

             // 确保懒加载资源加载
             siblings.find('img[data-src]').each(function () {
                 $(this).attr('src', $(this).data('src')); // Replace data-src with src
             });

             // 如果是通过链接跳转过来的，找到对应的topic并展开
             if (isFromOtherPage) {
                 var titleElement = $(this).closest('.title');
                 var topicElement = titleElement.closest('.topic');
                 
                 // 如果有目标ID，尝试匹配
                 if (targetTopicId) {
                     // 检查当前topic或其中的元素是否匹配目标ID
                     if (topicElement.attr('id') === targetTopicId || 
                         topicElement.find('[id="' + targetTopicId + '"]').length > 0) {
                 $(this).addClass('expanded');
                         siblings.show();
                         
                         // 预加载图片
                         siblings.find('img[data-src]').each(function () {
                             $(this).attr('src', $(this).data('src'));
                         });
                         
                         // 滚动到目标位置
                         setTimeout(function() {
                             var targetElement = $('#' + targetTopicId);
                             if (targetElement.length) {
                                 $('html, body').animate({
                                     scrollTop: targetElement.offset().top - 20
                                 }, 300);
                             }
                         }, 100);
                         
                         return true; // 继续循环
                     }
                 } else {
                     // 如果没有特定目标ID，默认展开第一个topic
                     if ($(this).closest('.topic').is(':first-child')) {
                         $(this).addClass('expanded');
                 siblings.show();
                         
                         // 预加载图片
                         siblings.find('img[data-src]').each(function () {
                             $(this).attr('src', $(this).data('src'));
                         });
                         
                         return true;
                     }
                 }
                 
                 // 非目标topic：移除expanded状态并隐藏内容
                 $(this).removeClass('expanded');
                 siblings.hide();
             } else {
                 // 非跳转访问：默认移除expanded状态并隐藏内容
                 $(this).removeClass('expanded');
                 siblings.hide();
             }
         });
     }
     
     
     });
 
 /**
  * Marks the hidden siblings of the matched nodes as being not expandable.
  *
  * @param nodes The matched nodes.
  */
 function markHiddenSiblingsAsNotExpandable(nodes) {
     var siblings = nodes.siblings(":hidden");// 所有隐藏的兄弟
     siblings.addClass("wh_not_expandable");
 }
 
 /*added by Tung to add icon*/
 $(document).ready(function () {
     var x = document.getElementsByClassName("hd");
     var i;
     for (i = 0; i < x.length; i++) {
         x[i].innerHTML = x[i].innerHTML + "<img src=\"../daksys-webhelp/resources/img/hd.png \" height=\"75\" width=\"75\" />"
     }
     var x = document.getElementsByClassName("water_proof");
     var i;
     for (i = 0; i < x.length; i++) {
         x[i].innerHTML =  x[i].innerHTML + "<img src=\"../daksys-webhelp/resources/img/waterproof.png \" height=\"75\" width=\"75\" />"
     }
     var x = document.getElementsByClassName("H265");
     var i;
     for (i = 0; i < x.length; i++) {
         x[i].innerHTML =  x[i].innerHTML + "<img src=\"../daksys-webhelp/resources/img/h265.png \" height=\"75\" width=\"75\" />"
     }
     var x = document.getElementsByClassName("motorized");
     var i;
     for (i = 0; i < x.length; i++) {
         x[i].innerHTML =  x[i].innerHTML + "<img src=\"../daksys-webhelp/resources/img/motorized.png \" height=\"75\" width=\"75\" />"
     }
     var x = document.getElementsByClassName("WDR");
     var i;
     for (i = 0; i < x.length; i++) {
         x[i].innerHTML =  x[i].innerHTML + "<img src=\"../daksys-webhelp/resources/img/wdr.png \" height=\"75\" width=\"75\" />"
     }
     var x = document.getElementsByClassName("DNR");
     var i;
     for (i = 0; i < x.length; i++) {
         x[i].innerHTML =  x[i].innerHTML + "<img src=\"../daksys-webhelp/resources/img/3ddnr.png \" height=\"75\" width=\"75\" />"
     }
     
 /*    This added to move the title*/
     $('.wt_topic_content>h1').each(function() {
         $(this).parent().parent().before(this);
     });
     
     $('#bodywrapper').addClass($('#lang').text());
     $('#content_area').addClass($('#lang').text());
     
 });
